/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface ProfileRecord {
    timestamp: Time;
    profile: Profile;
}
export interface ShareBackInput {
    name: string;
    email: string;
    message: string;
    phone: string;
}
export interface ShareBack {
    name: string;
    email: string;
    message: string;
    timestamp: Time;
    phone: string;
}
export interface ProfileFilter {
    hasPets?: boolean;
    hasElderlyLovedOnes?: boolean;
    firstNameContains?: string;
    companyContains?: string;
}
export interface Profile {
    bio: string;
    hasPets: boolean;
    hasElderlyLovedOnes: boolean;
    socialLinks: {
        linkedin: string;
        twitter: string;
        instagram: string;
        facebook: string;
    };
    email: string;
    website: string;
    company: string;
    jobTitle: string;
    address: {
        zip: string;
        street: string;
        country: string;
        city: string;
        state: string;
    };
    phone: string;
    lastName: string;
    firstName: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createOrReplaceProfile(phone: string, profile: Profile): Promise<void>;
    deleteAllProfiles(): Promise<void>;
    deleteProfile(phone: string): Promise<void>;
    getCallerUserRole(): Promise<UserRole>;
    getFilteredProfiles(filter: ProfileFilter): Promise<Array<ProfileRecord>>;
    getProfile(phone: string): Promise<ProfileRecord | null>;
    getProfileCount(): Promise<bigint>;
    getProfileHistory(phone: string): Promise<Array<ProfileRecord>>;
    getProfilesWithElderlyLovedOnes(): Promise<Array<ProfileRecord>>;
    getProfilesWithPets(): Promise<Array<ProfileRecord>>;
    getShareBacks(ownerPhone: string): Promise<Array<ShareBack>>;
    isCallerAdmin(): Promise<boolean>;
    listProfiles(): Promise<Array<ProfileRecord>>;
    searchProfilesByCompany(company: string): Promise<Array<ProfileRecord>>;
    searchProfilesByName(name: string): Promise<Array<ProfileRecord>>;
    submitShareBack(ownerPhone: string, input: ShareBackInput): Promise<void>;
}
import type { ProfileFilter as _ProfileFilter, ProfileRecord as _ProfileRecord, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createOrReplaceProfile(arg0: string, arg1: Profile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrReplaceProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrReplaceProfile(arg0, arg1);
            return result;
        }
    }
    async deleteAllProfiles(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllProfiles();
            return result;
        }
    }
    async deleteProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProfile(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFilteredProfiles(arg0: ProfileFilter): Promise<Array<ProfileRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFilteredProfiles(to_candid_ProfileFilter_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFilteredProfiles(to_candid_ProfileFilter_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getProfile(arg0: string): Promise<ProfileRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfileCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfileCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfileCount();
            return result;
        }
    }
    async getProfileHistory(arg0: string): Promise<Array<ProfileRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfileHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfileHistory(arg0);
            return result;
        }
    }
    async getProfilesWithElderlyLovedOnes(): Promise<Array<ProfileRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfilesWithElderlyLovedOnes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfilesWithElderlyLovedOnes();
            return result;
        }
    }
    async getProfilesWithPets(): Promise<Array<ProfileRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfilesWithPets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfilesWithPets();
            return result;
        }
    }
    async getShareBacks(arg0: string): Promise<Array<ShareBack>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShareBacks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShareBacks(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listProfiles(): Promise<Array<ProfileRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProfiles();
            return result;
        }
    }
    async searchProfilesByCompany(arg0: string): Promise<Array<ProfileRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProfilesByCompany(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProfilesByCompany(arg0);
            return result;
        }
    }
    async searchProfilesByName(arg0: string): Promise<Array<ProfileRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProfilesByName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProfilesByName(arg0);
            return result;
        }
    }
    async submitShareBack(arg0: string, arg1: ShareBackInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitShareBack(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitShareBack(arg0, arg1);
            return result;
        }
    }
}
function from_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProfileRecord]): ProfileRecord | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_ProfileFilter_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfileFilter): _ProfileFilter {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasPets?: boolean;
    hasElderlyLovedOnes?: boolean;
    firstNameContains?: string;
    companyContains?: string;
}): {
    hasPets: [] | [boolean];
    hasElderlyLovedOnes: [] | [boolean];
    firstNameContains: [] | [string];
    companyContains: [] | [string];
} {
    return {
        hasPets: value.hasPets ? candid_some(value.hasPets) : candid_none(),
        hasElderlyLovedOnes: value.hasElderlyLovedOnes ? candid_some(value.hasElderlyLovedOnes) : candid_none(),
        firstNameContains: value.firstNameContains ? candid_some(value.firstNameContains) : candid_none(),
        companyContains: value.companyContains ? candid_some(value.companyContains) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
